storage: /verdaccio/storage

web:
  title: Tokotuku local registry

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    max_users: -1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  "@tokotuku/*":
    access: $all
    publish: $all
    unpublish: $all

  "**":
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

middlewares:
  audit:
    enabled: true

log:
  type: stdout
  format: pretty
  level: http
